// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API backend format selection
 */
export type ApiBackend = "ChatCompletions" | "Messages" | "Generic";
