// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallItem } from "./ToolCallItem";

/**
 * Unified conversation item for internal representation
 */
export type ConversationItem = { "role": "system", content: string, } | { "role": "user", content: string, images: Array<string> | null, } | { "role": "assistant", content: string, tool_calls: Array<ToolCallItem> | null, } | { "role": "tool_result", tool_call_id: string, content: string, } | { "role": "reasoning", content: string, signature: string | null, };
