// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiBackend } from "./ApiBackend";
import type { AuthScheme } from "./AuthScheme";

/**
 * Provider configuration
 */
export type ProviderConfig = { name: string, base_url: string, api_key: string, auth_scheme: AuthScheme, backend: ApiBackend, models: Array<string>, enabled: boolean, };
