// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reasoning mode configuration
 */
export type ReasoningMode = "Disabled" | "Light" | "Medium" | "Deep";
