// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Channel type for streamed content
 */
export type SamplingChannel = "Text" | "Reasoning";
