// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiBackend } from "./ApiBackend";
import type { ConversationItem } from "./ConversationItem";
import type { ReasoningMode } from "./ReasoningMode";
import type { ToolSpec } from "./ToolSpec";

/**
 * Unified request type
 */
export type SamplingRequest = { request_id: string, model: string, backend: ApiBackend, messages: Array<ConversationItem>, tools: Array<ToolSpec> | null, temperature: number | null, max_tokens: number | null, reasoning_mode: ReasoningMode | null, };
