// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SamplingChannel } from "./SamplingChannel";

/**
 * Unified sampling event type for all providers.
 * Emitted throughout the streaming lifecycle.
 */
export type SamplingEvent = { "type": "streamStarted", request_id: string, timestamp_ms: bigint, } | { "type": "firstToken", request_id: string, } | { "type": "channelToken", request_id: string, channel: SamplingChannel, text: string, chunk_index: number, } | { "type": "toolCallStart", request_id: string, tool_index: number, id: string, name: string, } | { "type": "toolCallDelta", request_id: string, tool_index: number, arguments_delta: string, } | { "type": "toolCallComplete", request_id: string, tool_index: number, arguments: string, } | { "type": "usage", request_id: string, prompt_tokens: number, completion_tokens: number, total_tokens: number, } | { "type": "completed", request_id: string, } | { "type": "failed", request_id: string, error: string, };
