// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool specification
 */
export type ToolSpec = { name: string, description: string, 
/**
 * JSON schema as string
 */
parameters: string, };
