// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool call representation in conversation
 */
export type ToolCallItem = { id: string, name: string, arguments: string, };
