/**
 * Shared tool icon mapping — used by ToolCallCard and PermissionDialog.
 *
 * Maps backend tool names to their corresponding Lucide icon components.
 */
import {
  FileText,
  FilePen,
  FileType2,
  Presentation,
  FolderOpen,
  Search,
  Braces,
  Terminal,
  Globe,
  HelpCircle,
  Brain,
  Network,
  Table2,
  Film,
  ScanText,
  BarChart3,
  FolderCog,
  MousePointerClick,
  Activity,
  BookMarked,
  BookOpen,
  Briefcase,
  CalendarClock,
  ClipboardList,
  CreditCard,
  Download,
  Eye,
  FolderSearch,
  Library,
  ListTodo,
  MapPin,
  Monitor,
  Package,
  PenLine,
  Server,
  Store,
  Target,
  Timer,
  Trash2,
  UserRound,
  Workflow,
  Wrench,
  XCircle,
  type LucideIcon,
} from "lucide-react";

export const TOOL_ICONS: Record<string, LucideIcon> = {
  read_file: FileText,
  write_file: FilePen,
  edit_file: FilePen,
  search_replace: FilePen,
  list_dir: FolderOpen,
  grep: Search,
  glob: Braces,
  bash: Terminal,
  run_command: Terminal,
  web_fetch: Globe,
  web_fetch_depwork: Globe,
  web_search: Search,
  ask_user: HelpCircle,
  task_manage: Network,
  memory_search: Brain,
  memory_store: Brain,
  agent: Network,

  // ── Depwork (document / media processing) tools ──────────────
  doc_read: FileText,
  doc_consistency: Search,
  docx_generate: FileType2,
  ppt_generate: Presentation,
  table_process: Table2,
  batch_file: FolderCog,
  ui_automate: MousePointerClick,
  web_open: Globe,
  media_probe: Film,
  media_convert: Film,
  ocr_image: ScanText,
  chart_generate: BarChart3,

  // ── Family-mapped tools (shared family icons) ───────────────
  apply_patch: FilePen,
  search_symbols: Search,
  file_dependencies: Network,
  lsp: Braces,
  kill_task: XCircle,
  memory_learn: Brain,
  monitor: Activity,
  enter_plan_mode: ClipboardList,
  exit_plan_mode: ClipboardList,
  scheduler_create: CalendarClock,
  scheduler_list: CalendarClock,
  scheduler_delete: CalendarClock,
  todo_write: ListTodo,
  update_goal: Target,
  use_tool: Wrench,
  user_profile: UserRound,
  visual_describe: Eye,
  wait_tasks: Timer,
  workflow: Workflow,
  browser_control: Globe,
  card_generate: CreditCard,
  docx_edit: FilePen,
  docx_search: Search,
  live_doc_write: PenLine,
  office_automate: Briefcase,
  pdf_generate: FileText,
  pdf_tools: FileText,
  research_search: Library,
  research_save: BookMarked,
  research_list: Library,
  research_remove: Trash2,
  research_export: Download,
  research_folder_search: FolderSearch,
  research_clip: BookMarked,
  research_report: BookOpen,
  research_open_access: BookOpen,
  citation_link: BookMarked,
  store_research_map: MapPin,
  store_research_xhs: Store,
  store_research_geo: MapPin,
  xlsx_generate: Table2,
  dev_browser_open: Monitor,
  content_pack: Package,
};

/** Fallback icon for unknown tool names. */
export const DEFAULT_TOOL_ICON: LucideIcon = Braces;

/** Get the icon for a tool name, falling back to the default. */
export function getToolIcon(name: string): LucideIcon {
  if (name.startsWith("mcp__")) return Server;
  return TOOL_ICONS[name] ?? DEFAULT_TOOL_ICON;
}
